### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by davidkhess** [Schwanksta/python-arcgis-rest-query#10]
Any chance Python 3 support could be added?

**Comment by Schwanksta** [comment]
Haven't done much in the python3 realm but I bet it'd be a pretty easy to transition. Want to take a crack at it?

**Comment by davidkhess** [comment]
Unfortunately, I decided to go direct and parse the ArcGIS response instead and am no longer using the module.

Before I switched tactics, I did correct a couple of "print" statements and a relative important that got the command line tool to at least load and print help.

**Comment by schwanksta** [comment]
Closed by this pull request: https://github.com/Schwanksta/python-arcgis-rest-query/pull/12
