### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by vielmetti** [Schwanksta/python-arcgis-rest-query#9]
Just downloaded and installed to try the sample, and it's not working as I expect:

```
Edwards-MacBook-Air:~ emv$ arcgis-get http://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Legislative/MapServer 0 --where="STATE = 15" > hawaii_congressional_districts.geojson
Traceback (most recent call last):
  File "/usr/local/bin/arcgis-get", line 35, in <module>
    print json.dumps(arc.get(args.layer[0], where=args.where, fields=args.fields, count_only=args.count_only))
  File "/usr/local/lib/python2.7/site-packages/arcgis/arcgis.py", line 141, in get
    features += [self.esri_to_geojson(feat, geom_parser) for feat in jsobj.get('features')]
TypeError: 'NoneType' object is not iterable
```

**Comment by ThomasThoren** [comment]
I've run into this problem as well.

**Comment by ThomasThoren** [comment]
@vielmetti, that example seems to work okay for me. The map server I was trying to download from ended up working fine once I overrode the default object ID field of "OBJECTID".

**Comment by Schwanksta** [comment]
@vielmetti Sorry for missing this for so long. Do you still have that problem? It works for me now, but I think one of those examples was broken for a while because of a change on the server it was accessing. I'll go back through them and try to fix any broken ones.
